### ISSUE TITLE
Some RDF Data Cube Integrity Constraints aren't checking constraints as we're not using an OWL reasoner and some statements are implicit. Complexity 13

### ISSUE THREAD

**Issue by ajtucker** [ONS-OpenData/gdp-sparql-tests#1]
E.g. IC 11 looks for qb:componentProperty, which is a superproperty of qb:dimension. In the DSD we're using qb:dimension, so the IC doesn't match any triples.

**Comment by mikeAdamss** [comment]
added a readme to document what I've changed: https://github.com/GSS-Cogs/gdp-sparql-tests
