### ISSUE TITLE
Relax test for measure value

### ISSUE THREAD

**Issue by ajtucker** [ONS-OpenData/gdp-sparql-tests#8]
We're allowing observations to have no measure value as long as they have a value for `sdmx:obsStatus` to explain why. These ICs need to be relaxed.

**Comment by roblinksdata** [comment]
https://github.com/GSS-Cogs/gdp-sparql-tests/blob/c42c550197b1bc585fe667c4ec4c2e55c1f1784e/tests/qb/qb-ics/ic-15-measure_dimension_consistent.sparql

**Comment by ajtucker** [comment]
This looks ok and appears to work.

Closed by https://github.com/GSS-Cogs/gdp-sparql-tests/pull/9.
